### ISSUE TITLE
how to create multi-record NDEF?  M24SR.writeUri() get overwritten by M24SR.writeText()

### ISSUE THREAD

**Issue by jcanderle** [stm32duino/M24SR64-Y#9]
I am trying to write more records into NFC tag via I2C using this library, but write methods form the M24SR class are writing data to the 1st NDEF record. I could not find method to change the record or how to append next record.

**Comment by cparata** [comment]
Hi @jcanderle ,
I guess that in order to create multi-record messages, you need to use the low level APIs of the classes Message and Record. You can give a look at the implementation of the "writeTxt", "writeUri", etc. and then try to combine them in the application code using just one message with something like that:

```
bool writeUriAndText(const char *text_uri, const char *text)
{
  bool success = false;

  //retrieve the NdefLib interface
  NDefLib::NDefNfcTag *tag = nfcTag.get_NDef_tag();

  //open the i2c session with the nfc chip
  if(tag->open_session()) {
    //create the NDef message
    NDefLib::Message msg;

    //create the URI record
    NDefLib::RecordURI rUri(NDefLib::RecordURI::HTTP_WWW, text_uri);
    rUri.set_as_first_record();
    msg.add_record(&rUri);

    //create the Text record
    NDefLib::RecordText rText(text);
    rText.set_as_last_record();
    msg.add_record(&rText);

    //write the tag
    if(tag->write(msg)) {
      success = true;
    } else {
      success = false;
    }
    //close the i2c session
    tag->close_session();
  } else {
    success = false;
  }
  return success;
}

```

I hope that it can help.
Best Regards,
Carlo

**Comment by jcanderle** [comment]
Thank you, now I understand how to do it. I have added the functions to the class itself. Thank you, Kudos to you.
